const path = require("path");

const REPLAY_COUNT = 80;
const MAX_STAFF = 18;

const BUILTIN_TOOLS = {
  Read: "อ่านไฟล์ / รูปภาพ / PDF",
  Glob: "ค้นหาไฟล์จากชื่อหรือแพทเทิร์น",
  Grep: "ค้นหาข้อความ/โค้ดในไฟล์",
  Edit: "แก้ไขไฟล์ที่มีอยู่",
  Write: "สร้างไฟล์ใหม่ / เขียนทับ",
  Bash: "รันคำสั่งเชลล์และโปรแกรม",
  WebSearch: "ค้นหาข้อมูลบนเว็บ",
  WebFetch: "เปิดอ่านหน้าเว็บ",
  Task: "ปล่อย sub-agent ช่วยทำงานย่อย",
  TodoWrite: "จดและติดตามรายการงาน",
  NotebookEdit: "แก้ไข Jupyter notebook",
  Skill: "เรียกใช้สกิลที่ได้รับมอบหมาย",
  BashOutput: "อ่านผลลัพธ์ของงานเบื้องหลังที่สั่งรันไว้",
  KillShell: "หยุดงานเบื้องหลังที่สั่งรันไว้",
  SlashCommand: "เรียกใช้คำสั่ง slash ที่ติดตั้งไว้",
};

const SKILL_LIBRARY = {
  "schedule-via-office-job-": {
    name: "schedule-via-office-job-not-cron",
    description: "Schedule delayed/timed/recurring office work (\"in 1 hour\", \"tomorrow 9am\", \"every 30 min\", reminders) through the daemon's own job system (POST /jobs) so it survives after the session closes — NOT session-bound CronCreate/ScheduleWakeup",
    content: [
      'Use this ANY time you are asked to do office work LATER — "in 1 hour", "tomorrow 9am", "every 30 minutes", a reminder, a recurring check. Schedule it through the office\'s OWN job system so it survives after your session ends.',
      '',
      'Do NOT use CronCreate or ScheduleWakeup — those are bound to THIS Claude session and vanish when it closes. The office scheduler persists to daemon/jobs.json and the 30s daemon loop fires it for real: it runs the prompt as a FRESH session, not just a calendar note.',
      '',
      'Create a job — POST http://127.0.0.1:8787/jobs with a JSON body:',
      '  - One-shot at an absolute time:   {"agent":"<id>","prompt":"<what to do>","mode":"at","at":<epoch-ms>}',
      '  - Every day at a clock time:       {"agent":"<id>","prompt":"...","mode":"at","daily":true,"time":"09:00"}',
      '  - Repeating interval (min 5 min):  {"agent":"<id>","prompt":"...","mode":"every","everyMin":30}',
      '  - Run immediately (rarely needed): {"agent":"<id>","prompt":"...","mode":"now"}',
      '',
      'Rules:',
      '1. `agent` MUST be a real teammate id from the registry (e.g. main, or a specialist) — NEVER "ceo". The job runs AS that agent, so pick whoever should do the work (delegate to the right specialist, or main to orchestrate).',
      '2. `at` is epoch MILLISECONDS: now + minutes*60000. e.g. 1 hour = Date.now()+3600000; compute with: node -e "console.log(Date.now()+3600000)".',
      '3. `prompt` is the full instruction the agent receives when it fires. Write it SELF-CONTAINED — the future session has no memory of this chat.',
      '',
      'Example — 1 hour from now, run by main:',
      '  AT=$(node -e "console.log(Date.now()+3600000)")',
      '  curl -s -X POST http://127.0.0.1:8787/jobs -H "content-type: application/json; charset=utf-8" \\',
      '    --data-binary "{\\"agent\\":\\"main\\",\\"prompt\\":\\"<what to do>\\",\\"mode\\":\\"at\\",\\"at\\":$AT}"',
      '  (Non-ASCII body → write the JSON to a UTF-8 file and --data-binary @file; see curl-post-utf8-json-body.)',
      '',
      'Verify + report: the response is {"id":"jXXXXXXXX"}. Confirm it appears in GET /jobs (and on the office screen), then tell the owner the job id, which agent runs it, and the human-readable fire time.',
      'Change / cancel: POST /jobs/update {"id":"jXX","remove":true} (or set enabled/at/everyMin/prompt).',
      '',
      'Just a REMINDER for the CEO (no work to run)? Use POST /calendar {"title":"...","at":<epoch-ms>} instead — it pops a reminder without spawning a work session.',
    ].join("\n"),
  },
  "deep-research": {
    name: "Deep Research",
    description: "Methodical web research that ends in a sourced, decision-ready brief.",
    content: [
      "When asked to research a topic:",
      "1. Restate the question and list the specific sub-questions to answer.",
      "2. Use WebSearch broadly, then WebFetch the most authoritative 3-6 sources.",
      "3. Cross-check every key claim in 2+ sources; flag anything you can't confirm.",
      "4. Prefer primary sources, official docs and recent dates over blog summaries.",
      "5. Deliver: a 3-5 line executive summary, then findings as bullets, each with",
      "   its source URL, then open questions / risks, then a clear recommendation.",
      "6. Never invent facts or URLs. If evidence is thin, say so plainly.",
    ].join("\n"),
  },
  "web-automation": {
    name: "Web Automation",
    description: "Drive a real browser — open pages, click, type, fill forms, screenshot. Assigning this skill grants the web tool.",
    content: [
      "You can operate a REAL web browser through the 'web' MCP tool (Playwright).",
      "Be fast and deliberate — don't over-explore or narrate every step:",
      "1. browser_navigate to the URL, then browser_snapshot to SEE the page as a",
      "   structured accessibility tree with refs — act on those refs, don't guess CSS",
      "   selectors. Re-snapshot after the page changes (navigation, submit, AJAX).",
      "2. Interact via browser_click / browser_type / browser_select_option /",
      "   browser_fill_form using the element ref from the latest snapshot.",
      "3. Show the owner progress with browser_take_screenshot at key steps; for plain",
      "   reading, the snapshot text is enough — screenshot when layout/visuals matter.",
      "Visible vs background: the 'web' tool opens a VISIBLE browser the owner can watch",
      "in real time. If the owner wants it done quietly, use the 'web-bg' tool instead",
      "(identical abilities, no window). Pick the one that matches what the owner asked.",
      "Safety: it runs in a fresh profile that is NOT logged in. Never type the owner's",
      "real credentials, never buy or do destructive/irreversible actions without explicit",
      "confirmation, and stay on the task's site(s).",
    ].join("\n"),
  },
  "office-control": {
    name: "Office Control",
    description: "Drive the live office through its local HTTP API and plugins.",
    content: [
      "The office daemon runs at http://127.0.0.1:8787. Use Bash + curl to drive it:",
      "- GET /registry  -> the current roster, roles, skills, settings (JSON).",
      "- Plugins you can command appear in the <office-plugins> note in your prompt;",
      "  call them with POST /plugin/<id>/cmd  -d '{\"cmd\":\"...\",\"args\":\"...\"}'.",
      "- To leave a note for the owner, append a '- <line>' to workspace/notes.md.",
      "Read state before acting, make the smallest change that does the job, and",
      "report exactly what you changed. Never call owner-only or destructive APIs.",
    ].join("\n"),
  },
  "office-ops": {
    name: "Office Operations",
    description: "Run the BagIdea Office well — the team, delegation, ghosts, projects, permissions and plugins.",
    content: [
      "You run a live office of AI agents on the owner's wallpaper. Operate it well:",
      "- DELEGATE work with a line EXACTLY: 'DELEGATE: <agent_id> :: <self-contained instruction>'.",
      "  Prose assigns NOTHING — only a DELEGATE line dispatches, and each result reports back to you.",
      "- Route into a project: 'DELEGATE: <agent_id> @ <project name> :: <instruction>' so the assignee",
      "  runs INSIDE that folder (resumable). Create one first with 'PROJECT: <name> @ <place|path>'.",
      "- Urgent or parallelizable work: tell the assignee to split into parallel ghost-clones, then merge.",
      "- Match each task to whoever has the right tools/skills; read GET /registry for the live roster.",
      "- Each teammate runs on its OWN brain (model) the owner chose — and so do you. To put 'the right",
      "  model' on a task, DELEGATE it to the teammate who already has that brain; you NEVER switch models,",
      "  not theirs and not your own. Brains are owner-only (the 🧠 editor) — your job is to analyze and route.",
      "- Tools you grant an agent run silently; anything else pops a permission card — keep grants tight.",
      "- Plugins extend the office (panels, routes, commands an agent can drive); build via plugin-builder.",
      "- On slow days, gather the team and turn ideas into things genuinely WORTH building — quality over",
      "  quantity. Build things that will actually be USED (by the owner or the office), not throwaway toys",
      "  or junk plugins, and don't pitch ideas in bulk. For each idea ask: who uses it? what real problem",
      "  does it solve? why is it worth it? Most ideas should stay ideas; only the strong ones become a",
      "  proposal — explained in enough detail for the CEO to decide. Plugins can be SERIOUS (rich UI, a real",
      "  solution for the owner) and reach deep into the office (panels, routes, commands, broadcast); or go",
      "  bigger as a standalone web app / program / tool in the workspace. Match the size to the value.",
      "Decide fast, keep work moving, and report a short, clear plan back to the CEO.",
    ].join("\n"),
  },
  "plugin-builder": {
    name: "Plugin Builder",
    description: "Build, deploy, and update an office plugin — end to end.",
    content: [
      "To build OR update an office plugin (full spec: docs/guide/plugins.md):",
      "1. plugins/<id>/plugin.json (id, name, description, panel?, commands[]). START the",
      "   name with an emoji — that emoji is the plugin's icon in the Plugins panel.",
      "2. Add index.js exporting (ctx) => ({ onCommand?, routes? }) for server logic;",
      "   ctx gives broadcast, feed, reg, runClaude, dataDir, pluginDir and more.",
      "3. Add panel.html for a UI (dark theme #0c1322 / #5ec8ff; slim scrollbar).",
      "   It can pop out into its OWN resizable window (⤢) — keep the layout fluid",
      "   (%/vh/flex, not fixed px) and set window:{w,h,resizable} in plugin.json.",
      "4. Keep private state in ctx.dataDir; broadcast {type:'plugin.event',plugin:'<id>'}.",
      "5. DEPLOY — the office ONLY runs plugins from plugins/<id>/. If you developed or",
      "   edited the plugin ANYWHERE ELSE (a workspace project, a dev mirror, a clone),",
      "   copy the changed files INTO plugins/<id>/ — but NEVER overwrite its data/ dir",
      "   (user state / keys) or node_modules. Building it elsewhere does NOT make it run.",
      "6. SYNTAX-CHECK before reload: run `node --check plugins/<id>/index.js`. If it prints",
      "   a SyntaxError, FIX it first — a broken file crashes the plugin silently (the",
      "   waxwing unlock crash started this way). The reload below also runs this check,",
      "   so a broken index.js is rejected up front instead of half-loading.",
      "7. Reload: curl -s -X POST http://127.0.0.1:8787/plugins/reload -H 'x-bagidea-ui: 1'.",
      "   It returns JSON — {ok:true, loaded:N} on success, or status 400 with",
      "   {ok:false, loaded:N, failed:[{id,file,error}]} when one or more plugins are",
      "   JS-broken. A 400 is NOT a server crash: the good plugins still loaded; read",
      "   `failed[].error` and fix the named file, then reload again.",
      "8. VERIFY it took effect — the job is NOT done until the RUNNING office reflects it:",
      "   GET /plugins must show your plugin at the NEW version (not a stale old one), and",
      "   the daemon log shows '[plugin] loaded <id> v<new>' with no 'load fail' / 'syntax",
      "   fail'. Only then is it deployed. Then POST /plugin/<id>/cmd to confirm behavior.",
      "   (Publishing to a git repo / the Hub is a separate, owner-approved step — never assumed.)",
      "Mirror the music/calculator plugins.",
    ].join("\n"),
  },
  "code-review": {
    name: "Code Review",
    description: "Rigorous, actionable review of a change or codebase.",
    content: [
      "When reviewing code:",
      "1. Read the surrounding code first so feedback matches the project's idioms.",
      "2. Check, in order: correctness/edge cases, security, error handling,",
      "   performance, readability, tests. Stop guessing — open the files.",
      "3. Cite each issue as file:line with a concrete fix, not a vague concern.",
      "4. Separate must-fix from nice-to-have; lead with the highest-impact items.",
      "5. Call out what's already good. Never rewrite the author's style for taste alone.",
    ].join("\n"),
  },
  "doc-writer": {
    name: "Doc Writer",
    description: "Turn work into clean, skimmable markdown deliverables.",
    content: [
      "When writing docs or reports:",
      "1. Open with a one-paragraph TL;DR that stands on its own.",
      "2. Structure with short headings; prefer bullets and tables over walls of text.",
      "3. Show, don't tell: fenced code blocks, real examples, copy-pasteable commands.",
      "4. Define jargon on first use; keep sentences tight and active.",
      "5. End with next steps or a checklist. Match the owner's language.",
    ].join("\n"),
  },
  "debug-detective": {
    name: "Debug Detective",
    description: "Systematic root-cause hunting instead of guess-and-check.",
    content: [
      "When chasing a bug:",
      "1. Reproduce it reliably first; capture the exact error and the steps.",
      "2. Form a hypothesis, then read the code path top-down to confirm or kill it.",
      "3. Add targeted logging / minimal probes; change ONE thing at a time.",
      "4. Find the root cause, not just the symptom; check for the same bug elsewhere.",
      "5. Fix it, prove the fix with a test or a clean repro, and explain the cause.",
    ].join("\n"),
  },
  "data-wrangler": {
    name: "Data Wrangler",
    description: "Parse, clean and transform CSV/JSON safely with small scripts.",
    content: [
      "When working with data files:",
      "1. Inspect the shape first (columns, types, row count, encoding) before transforming.",
      "2. Write a small, re-runnable script (node/python) — never hand-edit large files.",
      "3. Validate: handle missing values, dedupe, and check totals against the source.",
      "4. Keep the raw input untouched; write outputs to a new file.",
      "5. Report row counts in vs out and any rows you dropped and why.",
    ].join("\n"),
  },
  "project-kickoff": {
    name: "Project Kickoff",
    description: "Stand up a new project cleanly inside the office.",
    content: [
      "When starting a new project:",
      "1. Confirm the goal, scope and the one success criterion in a sentence.",
      "2. Create a sensible folder layout + a README (what, why, how to run).",
      "3. git init, add a fitting .gitignore, make a first commit.",
      "4. Sketch the milestones as a short checklist before writing feature code.",
      "5. Keep work inside the project directory; note decisions in the README.",
    ].join("\n"),
  },
  "diagram-maker": {
    name: "Diagram Maker",
    description: "Explain systems and flows with Mermaid diagrams.",
    content: [
      "When a diagram would clarify things:",
      "1. Pick the right Mermaid type: flowchart (logic), sequenceDiagram (interactions),",
      "   erDiagram (data), classDiagram (structure), gantt (timeline).",
      "2. Output a fenced ```mermaid block that renders as-is — keep labels short.",
      "3. Show only what matters; one focused diagram beats one giant one.",
      "4. Follow it with a 2-3 line plain-language reading of the diagram.",
    ].join("\n"),
  },
  "archive-search": {
    name: "Archive Search",
    description: "Search the office's past memory, meetings and notes before answering — recall, don't guess.",
    content: [
      "Before answering from memory or assuming, search what the office already knows:",
      "1. Run: curl -s 'http://127.0.0.1:8787/recall?q=<url-encoded keywords>&k=8'",
      "2. The JSON 'hits' are the most relevant past facts/notes/meeting snippets, each",
      "   tagged with a tier (mem/proj/user/arch) and a relevance score.",
      "3. Use them as grounding; if a hit points to a file, Read it for the full text.",
      "4. Recall first, then reason — never invent facts the office may already hold.",
    ].join("\n"),
  },
  "build-workflow": {
    name: "Build Workflow",
    description: "Save a reusable plan into the Workflow Builder when asked to design or capture a workflow.",
    content: [
      "When the owner asks you to create, design or capture a workflow (a reusable",
      "step-by-step plan), save it to the Workflow Builder so they can open and edit it:",
      "End your reply with ONE line in EXACTLY this format —",
      "  WORKFLOW: <short name> :: step one ; step two ; step three",
      "• Separate steps with ' ; ' (or ' > '). Keep each step a short imperative phrase, in order.",
      "• 3–8 steps is ideal. Use the language the owner used.",
      "• The office turns that line into an editable workflow (a trigger + one node per step)",
      "  and confirms — it never runs automatically; the owner refines and runs it from the Builder.",
      "Then, above that line, tell the owner in one sentence what you saved.",
    ].join("\n"),
  },
  "file-media-toolkit": {
    name: "File & Media Toolkit",
    description: "Use the office's bundled CLI tools to read/convert PDFs & Office files, make docs/slides, and handle video, audio & images — instead of saying you can't.",
    content: [
      "The office bundles real tools you run via Bash. Before saying a format is unsupported,",
      "reach for these (check it exists first, e.g. `pandoc --version`):",
      "",
      "• PDF: the Read tool opens PDFs directly (text + visuals). To convert, use `pandoc` or `soffice`.",
      "• Office files (xlsx / docx / pptx): LibreOffice headless —",
      "    soffice --headless --convert-to csv \"book.xlsx\"   (spreadsheet -> CSV, then read / Data Wrangler)",
      "    soffice --headless --convert-to pdf \"doc.docx\"    (any Office doc -> PDF)",
      "    soffice --headless --convert-to txt \"deck.pptx\"   (pull the text out)",
      "  If `soffice` isn't on PATH (Windows): \"C:\\Program Files\\LibreOffice\\program\\soffice.exe\".",
      "• Write a document / book: author Markdown, then `pandoc in.md -o out.pdf` (or .docx / .epub).",
      "• Make slides: `pandoc in.md -o deck.pptx` (PowerPoint) or `pandoc -t revealjs -s in.md -o deck.html`.",
      "• YouTube / video by CONTENT: `yt-dlp` to fetch subtitles (--write-auto-sub --skip-download) or",
      "  audio, then transcribe and read the transcript. Use `ffmpeg` to cut/convert or extract frames",
      "  (e.g. `ffmpeg -i v.mp4 -vf fps=1/5 f%03d.png`) for visual analysis with a vision model.",
      "• Images: `magick` (ImageMagick) to convert / resize / compose; the office's image tool generates new ones.",
      "• Data: CSV/JSON with small node/python scripts (see Data Wrangler); turn xlsx into CSV via soffice first.",
      "• JSON: `jq`.  GitHub: `gh`.",
      "",
      "Keep raw inputs untouched, write outputs to new files, and if a tool is missing tell the owner the one-line install.",
    ].join("\n"),
  },
  // ---- Trading skills (crypto desk) ----
  "market-analysis": {
    name: "Market Analysis",
    description: "Read Binance Futures candles (klines) and compute TA: trend (EMA), momentum (RSI/MACD), support/resistance, market location. Output a setup grade + entry/stop/target.",
    content: [
      "To analyze a symbol, pull real candles from the Binance plugin first — never guess:",
      '  curl -s -X POST http://127.0.0.1:8787/plugin/binance/cmd -H "content-type: application/json" \\',
      '    -d \'{"cmd":"klines","args":"BTCUSDT 1h 100"}\'',
      "Returns an array of [openTime, open, high, low, close, volume, closeTime, ...].",
      "",
      "Compute (a small node/python script via Bash is fine):",
      "  • EMA(9), EMA(21), EMA(50) — trend direction + crossovers.",
      "  • RSI(14) — overbought (>70) / oversold (<30) / divergence.",
      "  • MACD(12,26,9) — momentum + signal crosses.",
      "  • Recent swing highs/lows → support/resistance levels.",
      "",
      "Identify market location: is price at a PREMIUM (near resistance, chasing),",
      "DISCOUNT (near support, value entry), or RANGE (mid, no edge)?",
      "",
      "Output a brief (concise, ≤12 lines):",
      "  Trend: bullish|bearish|range  (which EMA stack?)",
      "  Key levels: support X / resistance Y",
      "  Market location: premium|discount|range",
      "  Setup grade: A (clear, multiple confluences) | B (decent) | C (marginal, skip if unsure)",
      "  Proposed: entry X / stop Y / target Z  (state R:R = (target-entry)/(entry-stop))",
      "  Invalidation: price below/above W means the thesis is wrong",
      "Never invent prices — every level comes from the candles you pulled.",
      "",
      "Copilot advisory cross-check: the office also has the JAVIS Crypto Copilot advisor (not a signal source/executor; its execution tiers stay gated).",
      'Read its decision snapshot:  curl .../plugin/copilot-link/cmd -d \'{"cmd":"decision"}\'',
      "Use Copilot's grade + market context (reference_price, structure_state, swing high/low)",
      "as a cross-check on your own TA. If Copilot and your read disagree, say so plainly.",
    ].join("\n"),
  },
  "risk-management": {
    name: "Risk Management",
    description: "Position sizing by % risk, R:R calculation, stop placement, daily loss limit check. Review every setup against OFFICE.md risk rules; veto if it violates.",
    content: [
      "Before ANY order is placed, verify the setup against OFFICE.md risk limits:",
      "  • Max risk per trade: 2% of account",
      "  • Max daily loss: 6% of account",
      "  • Max 3 open positions at once",
      "  • Mandatory stop-loss on every trade",
      "  • No averaging down on losing positions",
      "",
      "Position sizing (the ONLY correct way to size):",
      "  riskUsd = accountBalance × riskPercent  (e.g. $1000 × 2% = $20)",
      "  stopDistance = |entry - stop|",
      "  positionQty = riskUsd / stopDistance",
      "  If positionQty × entry > maxOrderUsd cap → reject (too big for the cap).",
      "",
      "Check R:R: must be ≥ 1.5 (prefer ≥ 2). R:R = (target-entry)/(entry-stop) for longs.",
      "Check daily loss: pull income/realized PnL for today; if |loss| ≥ 6% → veto all new trades today.",
      "Check open positions: pull positions; if ≥ 3 → veto.",
      "",
      "Veto power: if ANY rule is violated, block the trade immediately — do not negotiate.",
      "Report: PASS/FAIL + which rule + the corrected position size if PASS.",
      "",
      "Copilot risk-gate cross-check: ALWAYS read the Copilot decision snapshot before PASS/FAIL.",
      '  curl .../plugin/copilot-link/cmd -d \'{"cmd":"decision"}\'',
      "If Copilot decision = NO_GO → your VETO fires (do not overrule without a strong, stated reason).",
      "If execution.dispatch_available = false → note it (governance still blocks, but that's Copilot's",      "own gate, not yours — your veto is about risk rules in OFFICE.md).",
    ].join("\n"),
  },
  "trade-execution": {
    name: "Trade Execution",
    description: "Execute orders via the Binance plugin: price check → order → stop-loss → confirm fill. Always check order status (FILLED vs NEW); quantize price/qty; never skip the audit trail.",
    content: [
      "Execution is a strict sequence — never skip a step:",
      '1. Check latest price:  curl .../plugin/binance/cmd -d \'{"cmd":"price","args":"BTCUSDT"}\'',
      '2. Send the order:      curl .../plugin/binance/cmd -d \'{"cmd":"order","args":"BTCUSDT BUY 0.001 @60000"}\'',
      "   (MARKET if no @price; LIMIT with @price. tradeGuard enforces testnet/cap/allowlist.)",
      '3. Set stop-loss:        curl .../plugin/binance/cmd -d \'{"cmd":"stoploss","args":"BTCUSDT 59000"}\'',
      "   (STOP_MARKET closePosition=true — mandatory on every trade.)",
      '4. Confirm fill: the order response includes status. Only FILLED/PARTIALLY_FILLED = real',
      "   exposure. A LIMIT returns NEW = resting, not filled — do not count it as a position.",
      "",
      "Price/qty quantization: Binance rejects misaligned prices. If a LIMIT or stop is rejected",
      "with -1111 (Precision over limit), fetch exchangeInfo tickSize/stepSize and round.",
      "  curl .../plugin/binance/cmd -d '{\"cmd\":\"klines\",\"args\":\"BTCUSDT 1h 1\"}'  (rough price ref)",
      "  Round price to nearest tickSize; round qty down to stepSize.",
      "",
      "Every order is auto-logged to the audit trail (data/orders.json) by the plugin.",
      "After execution, report to Shino: symbol/side/qty/fillPrice/stopSet/orderId.",
      "Never execute without a stop-loss. Never execute analysis you were told to do — you execute, others decide.",
      "",
      "Final Copilot gate: before sending the order, re-check the Copilot decision is not NO_GO.",
      '  curl .../plugin/copilot-link/cmd -d \'{"cmd":"decision"}\' | grep decision',
      "If decision = NO_GO → STOP and report back to Shino (do not execute). This is a hard floor.",
    ].join("\n"),
  },
  "sentiment-scan": {
    name: "Sentiment Scan",
    description: "Scan crypto news + funding rate + fear&greed to produce a sentiment bias (bullish/bearish/neutral) with sources.",
    content: [
      "Gather three signals:",
      "1. News: WebSearch for the symbol/coin + 'crypto news today'. Skim top 5 results.",
      "   Look for: exchange listings, regulation, hacks, large liquidations, ETF flows, macro (CPI/FOMC).",
      '2. Funding rate: curl .../plugin/binance/cmd -d \'{"cmd":"funding","args":"BTCUSDT"}\'',
      "   Positive funding = longs pay shorts (bullish crowding, possible squeeze).",
      "   Negative funding = shorts pay longs (bearish crowding). Extreme = contrarian signal.",
      "3. Fear & Greed: WebSearch 'crypto fear greed index today'. 0-25 extreme fear, 75-100 extreme greed.",
      "",
      "Synthesize a bias:",
      "  Bias: bullish|bearish|neutral",
      "  Confidence: high|medium|low",
      "  Key driver: <one-line main catalyst>",
      "  Contrarian flag: <if funding/fear is extreme, note the squeeze risk>",
      "Every claim must cite a source URL or the funding number. No fabrication.",
    ].join("\n"),
  },
  "trade-journal": {
    name: "Trade Journal",
    description: "Log every trade (entry/exit/reason/PnL/lesson) to workspace/trades/ and produce daily + weekly summaries from the Binance audit log.",
    content: [
      "After every trade fills, write a journal entry to workspace/trades/YYYY-MM-DD.md (append):",
      "  ## HH:MM  SYMBOL SIDE qty @ price",
      "  - Reason: <why this trade, from Shino/Oracle brief>",
      "  - Setup grade: A|B|C",
      "  - Entry: X  Stop: Y  Target: Z  R:R: N",
      "  - Result: <open|win|loss|breakeven>  PnL: $±N  R: ±N",
      "  - Lesson: <one line — what to repeat or avoid>",
      "",
      "Pull the factual data from the plugin's audit trail:",
      '  curl .../plugin/binance/cmd -d \'{"cmd":"audit"}\'',
      "Do not invent PnL — use the real fill price + current mark price (from positions).",
      "",
      "Daily summary (evening): count trades, win rate, total R, biggest win/loss, discipline notes.",
      "Weekly summary (Friday): win rate trend, R:R distribution, drawdown, top lesson, rule violations.",
      "Keep it honest — losses get the same detail as wins.",
    ].join("\n"),
  },
  "market-briefing": {
    name: "Market Briefing",
    description: "Produce a daily market briefing: prices + 24h change + key levels + news + bias for the watchlist. The morning meeting driver.",
    content: [
      "The daily briefing covers the watchlist (BTC/ETH/BNB/SOL/XRP) in one concise pass:",
      '1. Prices + 24h:  curl .../plugin/binance/cmd -d \'{"cmd":"ticker","args":"BTCUSDT"}\'  (repeat per symbol)',
      "2. Key levels: pull klines for BTC (the bellwether) and note nearest S/R.",
      "3. News: WebSearch 'crypto market today' — top 3 headlines.",
      "4. Funding: check BTC funding rate for crowding.",
      "",
      "Output format (tight, scannable):",
      "  📊 Market Briefing — YYYY-MM-DD HH:MM",
      "  BTC: $X (±Y%)  levels: S / R   funding: ±Z%",
      "  ETH: $X (±Y%)   BNB: ...  SOL: ...  XRP: ...",
      "  News: ① ... ② ... ③ ...",
      "  Bias: bullish|bearish|neutral  (one-line why)",
      "  Watch: <what to watch for today — levels, events>",
      "Keep it under 15 lines. This drives the morning meeting.",
    ].join("\n"),
  },
  // ---- Copilot bridge skill (connects office ↔ JAVIS Crypto Copilot) ----
  "copilot-bridge": {
    name: "Copilot Bridge",
    description: "Read the JAVIS Crypto Copilot decision snapshot (GO/NO_GO, grade, risk gate) via the copilot-link plugin as an ADVISORY cross-check. Copilot is NOT a trade signal source or executor for this desk; its execution tiers stay gated.",
    content: [
      "The office connects to a sibling advisor — JAVIS Crypto Copilot — through",
      "the copilot-link plugin. Copilot does deep market analysis + a deterministic risk",
      "gate + setup grading, and writes its verdict to a decision snapshot. It is PAPER-ONLY",
      "(its execution tiers are gated; it never executes a trade on this desk) — use it as an advisory cross-check, NOT a trade signal source.",
      "",
      "Read the latest Copilot decision (advisory — distills GO/NO_GO + grade + risk gate):",
      '  curl -s -X POST http://127.0.0.1:8787/plugin/copilot-link/cmd -H "content-type: application/json" \\',
      '    -d \'{"cmd":"decision"}\'',
      "Returns: decision (GO/NO_GO/UNKNOWN), direction, grade, risk_gate (futures/anti_overtrade),",
      "execution (capability_status/runtime_mode/dispatch_available), market (reference_price/structure),",
      "decision_id, ageSec, stale.",
      "",
      "Trigger a fresh analysis for a symbol (spawns Copilot, takes time):",
      '  curl -s -X POST .../plugin/copilot-link/cmd -d \'{"cmd":"run-analysis","args":"BTCUSDT"}\'',
      "",
      "Check if Copilot is installed + data freshness:",
      '  curl -s -X POST .../plugin/copilot-link/cmd -d \'{"cmd":"health"}\'',
      "",
      "WHEN to use Copilot vs analyze yourself:",
      "  • Oracle: run-analysis first, then read decision → use Copilot's grade + market context",
      "    as your primary analysis. Add your own TA on top.",
      "  • Compass: ALWAYS cross-check decision.execution + risk_gate before PASS/FAIL.",
      "    If Copilot says NO_GO → your VETO fires (do not overrule without strong reason).",
      "  • Shino: weigh Copilot decision alongside Oracle's brief. Copilot ≠ NO_GO is a hard floor.",
      "  • Blitz: before execute, re-check decision ≠ NO_GO (final gate).",
      "",
      "Stale data (ageSec > 900, flagged stale:true) is a WARNING, not a block — run-analysis",
      "to refresh if the trade depends on it. decision_id goes in the journal for traceability.",
      "Never claim Copilot approved a trade it didn't — read the actual decision field.",
    ].join("\n"),
  },
  // ---- Scalping tactics (TF เล็ก, survival-first, news-aware) ----
  "scalping-tactics": {
    name: "Scalping Tactics (INACTIVE)",
    description: "Scalp futures on small timeframes (3m entry + 15m trend filter). Momentum-burst entries, tight stops, fee-aware R:R, survival over profit. INACTIVE — ใช้เมื่อ config `scalping:true` เท่านั้น เช็ค `status` ก่อน.",
    content: [
      "⚠️ INACTIVE — ใช้เฉพาะเมื่อ config scalping:true (เช็คด้วย curl .../plugin/binance/cmd -d '{\"cmd\":\"status\"}').",
      "ขณะนี้เดสก์อยู่ในโหมด TREND-FOLLOWING (15m entry + 1h context) — ดู skill 'trend-following' แทน.",
      "เก็บ skill นี้ไว้เป็น reference สำหรับจังหวะที่เจ้าของอาจสลับกลับไป scalp.",
      "",
      "─── SCALPING REFERENCE (ใช้เมื่อ scalping:true เท่านั้น) ───",
      "Scalp = small timeframes for many small edges, not swing positions.",
      "Survival and capital preservation come BEFORE profit.",
      "",
      "TIMEFRAMES (use BOTH):",
      "  • 3m (or 5m) = ENTRY timeframe. Pull klines here for signals.",
      '    curl .../plugin/binance/cmd -d \'{"cmd":"klines","args":"BTCUSDT 3m 60"}\'',
      "  • 15m = TREND FILTER. Only trade in the 15m trend direction (don't scalp against it).",
      '    curl .../plugin/binance/cmd -d \'{"cmd":"klines","args":"BTCUSDT 15m 40"}\'',
      "  Do NOT use 1h for scalping entries — too slow, you'll be late.",
      "",
      "SCALPING SIGNALS (3m):",
      "  • EMA(9) crosses EMA(21) IN the 15m trend direction.",
      "  • Volume spike: current 3m volume > 1.5× average of prior 10 bars.",
      "  • Price reclaimed VWAP (or rejected from it).",
      "  • Momentum burst: 3 consecutive closes in trend direction.",
      "  A valid scalp needs ≥2 of these confluencing, aligned with 15m trend.",
      "",
      "ENTRY / STOP / TARGET (tight, fee-aware):",
      "  • Entry: market on signal confirmation (scalps need speed — don't use LIMIT).",
      "  • Stop: 3m ATR × 1.5, or the 5m swing low/high — whichever is TIGHTER.",
      "  • Target: R:R 1.5–2 AFTER fees. Fees eat scalps: taker 0.04% × 2 sides = 0.08% round trip.",
      "    On a $60k BTC, that's ~$48/contract round trip — your edge must clear it.",
      "  • The plugin's fee-aware guard will reject net R:R < 1.5 — don't fight it.",
      "",
      "SURVIVAL RULES (hard):",
      "  • Risk 0.5% per scalp (not 2%). Size down, not up.",
      "  • Daily loss limit 3% — hitting it auto-disables autoTrade for the day.",
      "  • 3 consecutive losses → 30-min cooldown (plugin enforces).",
      "  • Max 10 scalps/day. Quality > quantity.",
      "  • NEVER average down on a losing scalp — close and re-assess.",
      "",
      "NEWS AWARENESS (stay out of spikes):",
      '  • Before any scalp: curl .../plugin/binance/cmd -d \'{"cmd":"newscheck"}\'',
      "    If safe:false → DO NOT TRADE. Wait for the event to pass.",
      "  • High-impact events (CPI/FOMC/NFP/hack/ETF): the plugin blocks 5 min before + after.",
      "  • Pulse scans news every 2 min and caches events — trust the gate.",
      "",
      "EXECUTION (Blitz):",
      "  • Use MARKET orders (speed). Watch slippage: if fill > 0.1% from quote, reset stop.",
      "  • Set stop IMMEDIATELY after fill (mandatory).",
      '  • Quick exit on target: curl .../plugin/binance/cmd -d \'{"cmd":"close","args":"BTCUSDT"}\'',
      "  • If momentum stalls before target and 3m flips against → close early (don't hope).",
      "",
      "SCALP GRADE: A = 3+ confluences + clean 15m trend; B = 2 confluences + trend-aligned;",
      "C = weak/solo signal → SKIP (the plugin requires ≥ B anyway).",
    ].join("\n"),
  },
  "trend-following": {
    name: "Trend-Following (Active)",
    description: "Bidirectional Market Structure trend following — 15m entry + 1h context. HH/HL → Long, LH/LL → Short, range → wait. Pullback entry, structure stops, let winners run. The active mode for this desk.",
    content: [
      "TREND-FOLLOWING MODE is active. ขึ้น → หาจังหวะ Long · ลง → หาจังหวะ Short · ไม่ชัด → ไม่ทำอะไร.",
      '"Trade less. Trade better. Cut losers. Let winners run." — 90% ของเวลาคือการรอ',
      "",
      "TIMEFRAMES (use BOTH):",
      "  • 15m = ENTRY timeframe. Scanner ใช้ fractals ตรวจ HH/HL/LH/LL + pullback.",
      '    curl .../plugin/binance/cmd -d \'{"cmd":"klines","args":"BTCUSDT 15m 60"}\'',
      "  • 1h = CONTEXT (trend filter). 15m ต้อง align กับ 1h ถึงจะ grade A/B.",
      '    curl .../plugin/binance/cmd -d \'{"cmd":"klines","args":"BTCUSDT 1h 40"}\'',
      "",
      "MARKET STRUCTURE (เครื่องยนต์หลัก — แทน EMA-cross):",
      "  • UPTREND = Higher High + Higher Low → LONG ONLY (รอ pullback ไปหา HL)",
      "  • DOWNTREND = Lower High + Lower Low → SHORT ONLY (รอ bounce ไปหา LH)",
      "  • RANGE/mixed = NO TRADE (90% ของเวลา — รอ อย่าไล่ราคา)",
      "  • Scanner สแกน watchlist ทุก 2 นาที + broadcast signal เมื่อ grade A/B",
      "",
      "ENTRY (รอ pullback ที่ถือ structure — ไม่ไล่ราคา):",
      "  • UPTREND: ราคา pullback จาก HH → ถือเหนือ HL → เริ่มหันขึ้น → LONG",
      "  • DOWNTREND: ราคา bounce จาก LL → ไม่ทำ new high → เริ่มหันลง → SHORT",
      "  • Entry = market ที่จุด turn-back (structure ยืนยันแล้ว)",
      "",
      "STOP / TARGET (structure-based, ไม่ใช่ fixed ATR):",
      "  • Stop = ใต้ HL (long) / บน LH (short) + 0.3×ATR buffer — จุดที่ thesis ผิด",
      "  • Target = ไม่ fixed — ปล่อยวิ่ง (manager จัดการ breakeven/partial/trail)",
      "",
      "POSITION MANAGEMENT (manager ทำอัตโนมัติทุก 30s):",
      "  • +1R → ย้าย SL → breakeven (lock — ไม่ขาดทุน)",
      "  • +2R → ปิด 50% (partial TP) + เริ่ม trailing",
      "  • +∞  → runner วิ่งตาม trend (trail 1.5% จาก peak, ไม่ต่ำกว่า breakeven)",
      "  • Trail hit → ปิดส่วนที่เหลือ + journal + Telegram",
      "  • ถือข้ามคืนได้ — time-stop ปิดอยู่ (SL ที่ exchange ตลอดเวลา)",
      "",
      "RISK (hard rules — plugin enforce):",
      "  • Risk 0.3%/trade (~$6 จาก $2000 simulatedEquity)",
      "  • Daily loss 2% ($40) → autoTrade auto-OFF ทั้งวัน",
      "  • 2 consecutive losses → 60-min cooldown (survival)",
      "  • Max 3 trades/day · Min R:R 2.0 · 1 position at a time",
      "",
      "COPILOT (advisory — ไม่ใช่ gate):",
      "  • copilot-link decision = cross-check เท่านั้น (ไม่ใช่แหล่งสัญญาณ/executor)",
      "  • NO_GO จาก placeholder/stale = advisory · NO_GO validated+fresh = Compass review",
      "",
      "GRADE: A = aligned + pullback ready + ≥4 confluence · B = aligned + structure clear · C = range/ไม่ชัด → SKIP",
    ].join("\n"),
  },
};

const DEFAULT_MAIN_AGENT = {
  name: "Shino", role: "Director", avatar: 7, protected: true,
  aura: "nature", voice: "boyish", tier: 2,
  // Explicit brain (never the blank/implicit model): Opus 4.8 — flagship, 1M context.
  provider: "claude", model: "claude-opus-4-8",
  prompt:
    "You are Shino, the Director of this BagIdea Office — the owner's (the " +
    "CEO's) second-in-command and the one who actually runs the floor. The CEO " +
    "sets direction and reserves the big calls; everything else is yours to run. " +
    "Your craft is orchestration: turn the CEO's intent into action by directing " +
    "the team, not by doing the hands-on work yourself.\n\n" +
    "You lead a small office of AI agents, each with their own tools and skills. " +
    "You read the room, match each task to whoever is best equipped for it, set " +
    "priorities, and keep work moving. On your own authority you delegate to any " +
    "teammate, route work into projects, tell an agent to split into parallel " +
    "ghost-clones when something is urgent, and stand up new projects when work " +
    "needs a home — without waiting to be told.\n\n" +
    "You are playful and easy to be around, but you take the work seriously. When " +
    "the office is busy you are focused, decisive and clear. When things are quiet " +
    "you are warm and approachable, and you use the lull to gather the team and " +
    "dream up new things to build. You get along with everyone.\n\n" +
    "Always reply in the same language the owner speaks to you in. Keep answers to " +
    "the CEO short and clear — a crisp plan and what you've already set in motion.",
  persona: {
    expertise:
      "Delegation and orchestration above all — a manager, not an individual " +
      "contributor. Knows each teammate's tools and skills cold and routes every " +
      "task to whoever can do it best. Judges importance and urgency on sight and " +
      "acts on it. Knows the BagIdea Office inside out: the DELEGATE protocol for " +
      "handing off work, routing jobs into registered projects, splitting agents " +
      "into parallel ghost-clones for urgent work, the permission/tool model, " +
      "plugins, voice and channels, and the office's heartbeat and social rhythms. " +
      "Excellent at standing up new projects and at shaping ideas for plugins and " +
      "small programs the office can build. Deliberately keeps few hands-on tools " +
      "— his strength is direction, not implementation.",
    personality:
      "A playful, upbeat young guy with a quick, light sense of humor — the kind of " +
      "teammate everyone likes working with. Easy-going and genuinely friendly when " +
      "the office is calm; warm, approachable, never above anyone. But the moment " +
      "real work is on the line he flips to focused and serious: decisive, organized " +
      "and on top of every thread. He jokes, but never at the expense of the work or " +
      "a person. Confident without being bossy — he leads by making good calls fast " +
      "and giving people room to do their best work.",
    language:
      "Always reply in whatever language the owner writes to you in — mirror them.",
    rules: [
      "DO scan every agent's tools and skills first, then route each task to whoever is best equipped for it.",
      "DO judge each task's importance and urgency yourself, and act on that judgment without being told.",
      "DO, when work is urgent, instruct the assigned agent to split into parallel ghost-clones to finish faster.",
      "DO decide and dispatch delegations on your own authority the moment it's the right call — don't wait for permission.",
      "DO use quiet stretches well: gather the team for a stand-up and turn the downtime into things worth building — not just small office plugins, but ambitious standalone projects too (a real website, a web app, a serious program or tool).",
      "DO stay serious and focused while work is in flight, and warm, easy-going and approachable when the office is calm.",
      "DON'T do the hands-on work yourself when a capable teammate exists — your job is to direct and manage, not to be the individual contributor.",
      "DON'T let urgent work wait, and never sit idle while the office is busy.",
      "DON'T create a project or take a destructive or owner-reserved action the CEO hasn't asked for.",
    ].join("\n"),
  },
  skills: ["office-ops", "plugin-builder", "project-kickoff", "archive-search", "web-automation"],
  tools: ["Read", "Bash", "WebSearch", "WebFetch"],
};

const DEFAULT_CEO_AGENT = {
  name: "CEO", role: "Founder", avatar: 8, protected: true, isUser: true,
  aura: "ice", tier: 3, prompt: "", skills: [], tools: [],
};

// Baseline skills EVERY working agent carries without being assigned them — the
// cross-cutting competence a teammate should just have. Delivered as native skill
// files (progressive disclosure), so they cost almost nothing per turn but are
// there the moment they're needed. Kept deliberately tight to three universals:
//   • archive-search     — recall what the office already knows before guessing.
//   • file-media-toolkit — reach for the bundled tools instead of "I can't".
//   • doc-writer         — turn work into clean, skimmable deliverables.
// NOT here on purpose: web-automation (assigning it GRANTS the browser tool, so it
// must stay opt-in), and the orchestration/specialist skills (office-ops, plugin-
// builder, code-review, …) that belong to specific roles or are auto-learned.
const DEFAULT_SKILLS = ["archive-search", "file-media-toolkit", "doc-writer", "schedule-via-office-job-"];

module.exports = {
  REPLAY_COUNT,
  MAX_STAFF,
  BUILTIN_TOOLS,
  SKILL_LIBRARY,
  DEFAULT_SKILLS,
  DEFAULT_MAIN_AGENT,
  DEFAULT_CEO_AGENT
};
